FROM ubuntu:24.04

COPY requirements.dev,package.lock .
RUN apt-get update && apt-get upgrade -y && apt install -y python@3.12 python-pip3 node@18 sqllite && \
    pip install -r requirements.dev && \
    npm install && \
    sqllite start

PUBLISH 5432
PUBLISH 8000